### ISSUE TITLE
PRIORITY and THRESHOLD

### ISSUE THREAD

**Issue by spzeno** [RoaLogic/plic#12]
The datasheet's section 4.3.1 says that 
![image](https://user-images.githubusercontent.com/45329062/221073430-d5f83f23-7a1f-48d2-a9d0-40d0d57db4c9.png)
I wonder that if both PRIORITY and THRESHOLD is 0, whether the interrupt will be masked?

**Comment by rherveille** [comment]
A priority of '0' means the interrupt is never generated. The PLIC spec says: "The priority value 0 is reserved to mean “never interrupt”, and interrupt priority increases with increasing integer values."

**Comment by spzeno** [comment]
thanks very much for your reply!
